SERVER_PORT: 8081

MYSQL_URL: jdbc:mysql://localhost:3306/sbs?serverTimezone=Etc/GMT-8
MYSQL_USERNAME: root
MYSQL_PASSWORD: '111111'
MYSQL_CONNECTION_TIMEOUT: 30000
MYSQL_IDLE_TIMEOUT: 600000
MYSQL_MAX_LIFE_TIME: 1800000
MYSQL_MIN_IDLE: 10
MYSQL_MAX_POOL_SIZE: 100
MYSQL_VALIDATION_TIME: 5000

MSG_GREET_PATT: dev Hello %s